pyproject.toml
requirements.txt

since the problematic package seems to be torch, as in [this thread](https://stackoverflow.com/questions/78641150/a-module-that-was-compiled-using-numpy-1-x-cannot-be-run-in-numpy-2-0-0/78641405#78641405) downgraded the numpy temporarily

downgraded to numpy 1.26

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/pr.yml
requirements-dev.lock
requirements.lock

- Configured reports, feature requests, documentation, and pull request templates to allow external users to suggest changes in the correct format.
- Decided on the semantic pull request convention for naming and added GitHub Actions for validating and labeling PRs.

feat: 16 naming conventions

---

.github/ISSUE_TEMPLATE/feature_request.yml

feat: Changed feature to feat

---

.pre-commit-config.yaml
docs/reference.md
pyproject.toml
src/meteors/image.py
src/meteors/lime.py
src/meteors/lime_base.py
src/meteors/utils/models/models.py
src/meteors/utils/utils.py
src/meteors/visualise/__init__.py
src/meteors/visualise/lime_visualise.py
tests/test_band_mask.py
tests/test_image.py
tests/test_lime.py

refactor: 35 refactor lime

---

docs/reference.md
src/meteors/lime_base.py
tests/test_lime.py
tests/test_models.py

fix: 42 bug doc lime fail

---

src/meteors/lime.py
src/meteors/utils/models/__init__.py
src/meteors/utils/models/models.py
tests/test_lime.py
tests/test_models.py

feat: Added lime for classification

---

src/meteors/image.py
tests/test_image.py

feat: Change orientation method

---

src/meteors/image.py
src/meteors/lime.py

fix: Ingored dask warning

---

docs/reference.md
pyproject.toml
src/meteors/__init__.py
src/meteors/hsi.py
src/meteors/lime.py
src/meteors/visualize/lime_visualize.py
tests/test_hsi.py
tests/test_lime.py
tests/test_lime_visualise.py
tests/test_models.py

fix: Changed from Image to HSI

---

pyproject.toml
src/meteors/hsi.py
src/meteors/lime.py
src/meteors/lime_base.py
src/meteors/utils/models/models.py
src/meteors/utils/utils.py
tests/test_hsi.py
tests/test_lime.py
tests/test_lime_visualise.py
tests/test_models.py
tests/test_utils.py

feat: lime segmentation support

---

pyproject.toml
src/meteors/hsi.py
src/meteors/lime.py
src/meteors/visualize/lime_visualize.py
tests/test_hsi.py
tests/test_lime.py
tests/test_lime_visualise.py
tests/test_models.py

fix: 60 bug when all attributes are equal to 0 the vizualizations fail

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
changelog.md
commit_processor.py
pyproject.toml
tests/test_commit_processor.py

feat: New release action added

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

fix: changed templates

---

.github/workflows/release.yml
pyproject.toml

this PR solves some of the issues that occured whilist releasing the package using the github actions. 
It turned out that there were some problems with rye versioning and correct command execution

fix: github action release workflow to pypi

---

src/meteors/utils/utils.py

```
import sys
from cloudsen12_models import cloudsen12
import matplotlib.pyplot as plt
img_local = torch.rand((622, 916))
model = cloudsen12.load_model_by_name(name="UNetMobV2_V1", weights_folder="cloudsen12_models")
import meteors as mt
import torch
import numpy as np
sentinel_central_wavelengths = [442.7, 492.4, 559.8, 664.6, 704.1, 740.5, 782.8, 832.8, 864.7, 945.1, 1373.5, 1613.7, 2202.4]
hsi_image = mt.HSI(image =  img_local, wavelengths=sentinel_central_wavelengths)
explainable_model = mt.utils.models.ExplainableModel(model.predict, problem_type="segmentation")
segmentation_mask = explainable_model(hsi_image.image)
segmentation_mask = torch.tensor(segmentation_mask)
plt.imshow(segmentation_mask)
classes_numb = len(torch.unique(segmentation_mask))
classes_numb
from …
```

fix: infinite loop in segmentation

---

src/meteors/attr/explainer.py
src/meteors/attr/input_x_gradients.py
src/meteors/attr/integrated_gradients.py
src/meteors/attr/lime.py
src/meteors/attr/lime_base.py
src/meteors/attr/noise_tunnel.py
src/meteors/attr/occlusion.py
src/meteors/attr/saliency.py
src/meteors/utils/utils.py
tests/attr/test_attribution_methods.py
tests/attr/test_explainer.py
tests/attr/test_lime.py
tests/attr/test_noise_tunnel.py
tests/utils/utils/test_utils.py

feat: 105 feat aggregation for segmentation integrated into explainer object

---

pyproject.toml

updating the version, because I forgot to do it in a PR xd

chore: update the project version

---

pyproject.toml
requirements-docs.txt

update package version and remove unnecessary files

chore: update package version

---

examples/hyperview_challenge/attr_showcase.ipynb

Suggested changes to HYPERVIEW tutorial

docs: changes to the HYPERVIEW tutorial

---

examples/segmentation/segmentation.ipynb

Some changes to the segmentation tutorial

docs: changes to the segmentation tutorial

---

README.md

docs: fixing a minor typo in readme

---

pyproject.toml

Thank you for contributing to Meteors! Please follow the guidelines below to ensure a smooth and efficient contribution process.
- …

chore: bump up the package version
